---
- name: Install Centralized Monitoring Stack
  hosts: central_server
  become: true
  tasks:
    - name: Deploy Prometheus
      containers.podman.podman_container:
        name: prometheus
        image: docker.io/prom/prometheus:latest
        state: started
        ports:
          - "9090:9090"

    - name: Deploy Alertmanager
      containers.podman.podman_container:
        name: alertmanager
        image: docker.io/prom/alertmanager:latest
        state: started
        ports:
          - "9093:9093"

    - name: Deploy Grafana
      containers.podman.podman_container:
        name: grafana
        image: docker.io/grafana/grafana:latest
        state: started
        ports:
          - "3000:3000"
        env:
          GF_SECURITY_ADMIN_PASSWORD: "admin"
